name: Deploy Glue Script and Update Job

on:
  push:
    branches:
      - main
    paths:
      - 'data_file/script.py'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 1. Update the ETL Script file inside S3
    - name: Upload Script to S3
      run: |
        aws s3 cp data_file/script.py s3://tf-code-bucket-shri/script.py

    # 2. Dynamically fetch account ID and update Glue Job Configuration
    - name: Update Glue Job Configuration
      run: |
        # Fetch the active AWS account ID dynamically to prevent cross-account errors
        ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
        
        # Execute the update command with your exact job and role configuration
        aws glue update-job \
          --job-name "tf-glue-job" \
          --job-update "Role=arn:aws:iam::${ACCOUNT_ID}:role/glue_service_role,Command={Name=glueetl,ScriptLocation=s3://tf-code-bucket-shri/script.py,PythonVersion=3}"